--[gRPC documentation]: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
local M = {
	-- Not an error; returned on success.
	OK = 0,

	-- The operation was cancelled, typically by the caller.
	--
	-- The gRPC framework will generate this error code when cancellation
	-- is requested.
	CANCELLED = 1,

	-- Unknown error. An example of where this error may be returned is
	-- if a Status value received from another address space belongs to
	-- an error-space that is not known in this address space. Also
	-- errors raised by APIs that do not return enough error information
	-- may be converted to this error.
	--
	-- The gRPC framework will generate this error code in the above two
	-- mentioned cases.
	UNKNOWN = 2,

	-- The client specified an invalid argument. Note that this differs
	-- from FAILED_PRECONDITION. INVALID_ARGUMENT indicates arguments
	-- that are problematic regardless of the state of the system
	-- (e.g., a malformed file name).
	--
	-- This error code will not be generated by the gRPC framework.
	INVALID_ARGUMENT = 3,

	-- The deadline expired before the operation could complete.
	-- For operations that change the state of the system, this error may be
	-- returned even if the operation has completed successfully. For
	-- example, a successful response from a server could have been delayed
	-- long enough for the deadline to expire.
	--
	-- The gRPC framework will generate this error code when the deadline is
	-- exceeded.
	DEADLINE_EXCEEDED = 4,

	-- Some requested entity (e.g., file or directory) was not found.
	--
	-- This error code will not be generated by the gRPC framework.
	NOT_FOUND = 5,

	-- The entity that a client attempted to create (e.g., file or directory)
	-- already exists.
	--
	-- This error code will not be generated by the gRPC framework.
	ALREADY_EXISTS = 6,

	-- The caller does not have permission to execute the specified operation.
	-- PERMISSION_DENIED must not be used for rejections caused by exhausting
	-- some resource (use RESOURCE_EXHAUSTED instead for those errors).
	-- It must not be used if the caller can not be identified (use
	-- UNAUTHENTICATED instead for those errors).
	--
	-- This error code will not be generated by the gRPC core framework,
	-- but expect authentication middleware to use it.
	PERMISSION_DENIED = 7,

	-- Some resource has been exhausted, perhaps a per-user quota, or
	-- perhaps the entire file system is out of space.
	--
	-- This error code will be generated by the gRPC framework in
	-- out-of-memory and server overload situations, or when a message is
	-- larger than the configured maximum size.
	RESOURCE_EXHAUSTED = 8,

	-- The operation was rejected because the system is not in a state
	-- required for the operation's execution. For example, directory
	-- to be deleted may be non-empty, an rmdir operation is applied
	-- to a non-directory, etc.
	--
	-- A litmus test that may help a service implementor in deciding
	-- between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE:
	--  (a) Use UNAVAILABLE if the client can retry just the failing call.
	--  (b) Use ABORTED if the client should retry at a higher-level
	--      (e.g., restarting a read-modify-write sequence).
	--  (c) Use FAILED_PRECONDITION if the client should not retry until
	--      the system state has been explicitly fixed. E.g., if an "rmdir"
	--      fails because the directory is non-empty, FAILED_PRECONDITION
	--      should be returned since the client should not retry unless
	--      they have first fixed up the directory by deleting files from it.
	--  (d) Use FAILED_PRECONDITION if the client performs conditional
	--      REST Get/Update/Delete on a resource and the resource on the
	--      server does not match the condition. E.g., conflicting
	--      read-modify-write on the same resource.
	--
	-- This error code will not be generated by the gRPC framework.
	FAILED_PRECONDITION = 9,

	-- The operation was aborted, typically due to a concurrency issue
	-- like sequencer check failures, transaction aborts, etc.
	--
	-- See litmus test above for deciding between FAILED_PRECONDITION,
	-- ABORTED, and UNAVAILABLE.
	--
	-- This error code will not be generated by the gRPC framework.
	ABORTED = 10,

	-- The operation was attempted past the valid range.
	-- E.g., seeking or reading past end of file.
	--
	-- Unlike INVALID_ARGUMENT, this error indicates a problem that may
	-- be fixed if the system state changes. For example, a 32-bit file
	-- system will generate INVALID_ARGUMENT if asked to read at an
	-- offset that is not in the range [0,2^32-1], but it will generate
	-- OUT_OF_RANGE if asked to read from an offset past the current
	-- file size.
	--
	-- There is a fair bit of overlap between FAILED_PRECONDITION and
	-- OUT_OF_RANGE. We recommend using OUT_OF_RANGE (the more specific
	-- error) when it applies so that callers who are iterating through
	-- a space can easily look for an OUT_OF_RANGE error to detect when
	-- they are done.
	--
	-- This error code will not be generated by the gRPC framework.
	OUT_OF_RANGE = 11,

	-- The operation is not implemented or is not supported/enabled
	-- in this service.
	--
	-- This error code will be generated by the gRPC framework. Most
	-- commonly, you will see this error code when a method implementation
	-- is missing on the server. It can also be generated for unknown
	-- compression algorithms or a disagreement as to whether an RPC should
	-- be streaming.
	UNIMPLEMENTED = 12,

	-- Internal errors. This means that some invariants expected by
	-- underlying system has been broken. If you see one of these errors,
	-- something is very broken.
	--
	-- This error code will be generated by the gRPC framework in several
	-- internal error conditions.
	INTERNAL = 13,

	-- The service is currently unavailable. This is a most likely a
	-- transient condition and may be corrected by retrying with a backoff.
	-- Note that it is not always safe to retry non-idempotent operations.
	--
	-- See litmus test above for deciding between FAILED_PRECONDITION,
	-- ABORTED, and UNAVAILABLE.
	--
	-- This error code will be generated by the gRPC framework during
	-- abrupt shutdown of a server process or network connection.
	UNAVAILABLE = 14,

	-- Unrecoverable data loss or corruption.
	--
	-- This error code will not be generated by the gRPC framework.
	DATA_LOSS = 15,

	-- The request does not have valid authentication credentials for
	-- the operation.
	--
	-- The gRPC framework will generate this error code when the
	-- authentication metadata is invalid or a Credentials callback fails,
	-- but also expect authentication middleware to generate it.
	UNAUTHENTICATED = 16,
}

-- Build a bidirectional map: M[name] = code AND M[code] = name. The reverse
-- direction lets gRPC client/server code translate a numeric `grpc-status`
-- back into a human-readable name (see service.lua / registrar.lua).
do	--reverse map
	local tmp = {}
	for k, v in pairs(M) do
		tmp[k] = v
	end
	for k, v in pairs(tmp) do
		M[v] = k
	end
end

return M
