import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/en/": [
    "",
    "benchmark",
    {
      text: "Tutorials",
      icon: "graduation-cap",
      prefix: "tutorials/",
      link: "tutorials/",
      children: "structure",
    },
    {
      text: "Guides",
      icon: "book",
      prefix: "guides/",
      link: "guides/",
      children: [
        "error-handling",
        "hot-reload",
        "http-best-practices",
        "logging-monitoring",
        "mysql-connection-pool",
        "tls-configuration",
      ],
    },
    {
      text: "API Reference",
      icon: "code",
      prefix: "reference/",
      link: "reference/",
      children: [
        { text: "silly", icon: "microchip", link: "silly" },
        { text: "silly.env", icon: "gear", link: "env" },
        { text: "silly.task", icon: "list-check", link: "task" },
        { text: "silly.time", icon: "clock", link: "time" },
        { text: "silly.signal", icon: "wave-square", link: "signal" },
        { text: "silly.logger", icon: "file-lines", link: "logger" },
        { text: "silly.hive", icon: "gears", link: "hive" },
        { text: "silly.console", icon: "terminal", link: "console" },
        { text: "silly.debugger", icon: "bug", link: "debugger" },
        { text: "silly.patch", icon: "wrench", link: "patch" },
        {
          text: "silly.adt",
          icon: "box",
          prefix: "adt/",
          collapsible: true,
          children: [
            { text: "silly.adt.buffer", icon: "box", link: "buffer" },
            { text: "silly.adt.queue", icon: "layer-group", link: "queue" },
          ],
        },
        {
          text: "silly.crypto",
          icon: "lock",
          prefix: "crypto/",
          collapsible: true,
          children: [
            { text: "silly.crypto.cipher", icon: "key", link: "cipher" },
            { text: "silly.crypto.hash", icon: "hashtag", link: "hash" },
            { text: "silly.crypto.hmac", icon: "shield-halved", link: "hmac" },
            { text: "silly.crypto.pkey", icon: "certificate", link: "pkey" },
          ],
        },
        {
          text: "silly.encoding",
          icon: "code",
          prefix: "encoding/",
          collapsible: true,
          children: [
            { text: "silly.encoding.json", icon: "file-code", link: "json" },
            { text: "silly.encoding.base64", icon: "code", link: "base64" },
          ],
        },
        {
          text: "silly.sync",
          icon: "lock",
          prefix: "sync/",
          collapsible: true,
          children: [
            { text: "silly.sync.channel", icon: "arrows-left-right", link: "channel" },
            { text: "silly.sync.mutex", icon: "lock", link: "mutex" },
            { text: "silly.sync.waitgroup", icon: "user-group", link: "waitgroup" },
          ],
        },
        {
          text: "silly.net",
          icon: "network-wired",
          prefix: "net/",
          collapsible: true,
          children: [
            { text: "silly.net (Low-level API)", icon: "layer-group", link: "/en/reference/net" },
            { text: "silly.net.tcp", icon: "plug", link: "tcp" },
            { text: "silly.net.udp", icon: "paper-plane", link: "udp" },
            { text: "silly.net.tls", icon: "lock", link: "tls" },
            { text: "silly.net.http", icon: "globe", link: "http" },
            { text: "silly.net.websocket", icon: "comments", link: "websocket" },
            { text: "silly.net.grpc", icon: "code-compare", link: "grpc" },
            { text: "silly.net.dns", icon: "magnifying-glass", link: "dns" },
            { text: "silly.net.cluster", icon: "server", link: "cluster" },
          ],
        },
        {
          text: "silly.store",
          icon: "database",
          prefix: "store/",
          collapsible: true,
          children: [
            { text: "silly.store.mysql", icon: "database", link: "mysql" },
            { text: "silly.store.redis", icon: "database", link: "redis" },
            { text: "silly.store.etcd", icon: "database", link: "etcd" },
          ],
        },
        {
          text: "silly.security",
          icon: "shield",
          prefix: "security/",
          collapsible: true,
          children: [
            { text: "silly.security.jwt", icon: "shield", link: "jwt" },
          ],
        },
        {
          text: "silly.metrics",
          icon: "chart-line",
          prefix: "metrics/",
          collapsible: true,
          children: [
            { text: "silly.metrics.counter", icon: "chart-line", link: "counter" },
            { text: "silly.metrics.gauge", icon: "chart-line", link: "gauge" },
            { text: "silly.metrics.histogram", icon: "chart-bar", link: "histogram" },
            { text: "silly.metrics.prometheus", icon: "fire", link: "prometheus" },
            { text: "silly.metrics.registry", icon: "book", link: "registry" },
            { text: "silly.metrics.collector", icon: "box-archive", link: "collector" },
            { text: "silly.metrics.labels", icon: "tags", link: "labels" },
          ],
        },
      ],
    },
    {
      text: "Concepts",
      icon: "lightbulb",
      prefix: "concepts/",
      link: "concepts/",
      children: "structure",
    },
  ],
});
