import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "教程",
      icon: "graduation-cap",
      prefix: "tutorials/",
      link: "tutorials/",
      children: "structure",
    },
    {
      text: "操作指南",
      icon: "book",
      prefix: "guides/",
      link: "guides/",
      children: "structure",
    },
    {
      text: "API参考",
      icon: "code",
      prefix: "reference/",
      link: "reference/",
      children: [
        { text: "silly", icon: "microchip", link: "silly" },
        { text: "silly.time", icon: "clock", link: "time" },
        { text: "silly.signal", icon: "wave-square", link: "signal" },
        { text: "silly.logger", icon: "file-lines", link: "logger" },
        { text: "silly.hive", icon: "gears", link: "hive" },
        { text: "silly.console", icon: "terminal", link: "console" },
        { text: "silly.debugger", icon: "bug", link: "debugger" },
        { text: "silly.patch", icon: "wrench", link: "patch" },
        {
          text: "silly.crypto",
          icon: "lock",
          prefix: "crypto/",
          collapsible: true,
          children: ["cipher", "hash", "hmac", "pkey"],
        },
        {
          text: "silly.encoding",
          icon: "code",
          prefix: "encoding/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "silly.sync",
          icon: "lock",
          prefix: "sync/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "silly.net",
          icon: "network-wired",
          prefix: "net/",
          collapsible: true,
          children: [
            { text: "silly.net (底层API)", link: "/reference/net" },
            "tcp",
            "udp",
            "tls",
            "http",
            "websocket",
            "grpc",
            "dns",
            "cluster"
          ],
        },
        {
          text: "silly.store",
          icon: "database",
          prefix: "store/",
          collapsible: true,
          children: ["mysql", "redis", "etcd"],
        },
        {
          text: "silly.security",
          icon: "shield",
          prefix: "security/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "silly.metrics",
          icon: "chart-line",
          prefix: "metrics/",
          collapsible: true,
          children: ["counter", "gauge", "histogram", "prometheus", "registry", "collector", "labels"],
        },
      ],
    },
    {
      text: "原理解析",
      icon: "lightbulb",
      prefix: "concepts/",
      link: "concepts/",
      children: "structure",
    },
  ],
});
