name: CI

on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          autotools
          make
          git
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-gcc
    - uses: actions/checkout@v4
    - shell: msys2 {0}
      run: |
        make TEST=ON
        ./silly test/test.lua --test.timer.checkdelta=500
  build-macosx:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew update
        brew install openssl autoconf
        brew link openssl --force
        pkg-config --cflags openssl
        pkg-config --libs openssl
    - uses: actions/checkout@v4
    - name: make
      run: |
        make TEST=ON
        ./silly test/test.lua --test.timer.checkdelta=500
  build-linux:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev autoconf
    - uses: actions/checkout@v4
    - name: make
      run: |
        make TEST=ON
        ./silly test/test.lua